language: generic 
sudo: required
services:
  - docker


before install:
  - docker build -t muzaffar454/docker-react -f dockerfile.dev .


script:
  - docker run -e CI=true muzaffar454/docker-react npm run test